#ifndef __KMAX_PMU_H__
#define __KMAX_PMU_H__

/*PMU BASE*/
#define PMU_BASE					0x105C0000

enum pmu_regs {
CENTRAL_SEQ_MIF_STATUS=0,

RST_STAT,

RESET_SEQUENCER_STATUS,

INFORM0,
INFORM1,
INFORM2,
INFORM3,

PS_HOLD_HW_TRIP,
PS_HOLD_SW_TRIP,

ATLAS_CPU0_STATUS,
DIS_IRQ_ATLAS_CPU0_LOCAL_STATUS,
DIS_IRQ_ATLAS_CPU0_CENTRAL_STATUS,
DIS_IRQ_ATLAS_CPU0_CPUSEQUENCER_STATUS,

ATLAS_CPU1_STATUS,
DIS_IRQ_ATLAS_CPU1_LOCAL_STATUS,
DIS_IRQ_ATLAS_CPU1_CENTRAL_STATUS,
DIS_IRQ_ATLAS_CPU1_CPUSEQUENCER_STATUS,

ATLAS_CPU2_STATUS,
DIS_IRQ_ATLAS_CPU2_LOCAL_STATUS,
DIS_IRQ_ATLAS_CPU2_CENTRAL_STATUS,
DIS_IRQ_ATLAS_CPU2_CPUSEQUENCER_STATUS,

ATLAS_CPU3_STATUS,
DIS_IRQ_ATLAS_CPU3_LOCAL_STATUS,
DIS_IRQ_ATLAS_CPU3_CENTRAL_STATUS,
DIS_IRQ_ATLAS_CPU3_CPUSEQUENCER_STATUS,

APOLLO_CPU0_STATUS,
DIS_IRQ_APOLLO_CPU0_LOCAL_STATUS,
DIS_IRQ_APOLLO_CPU0_CENTRAL_STATUS,
DIS_IRQ_APOLLO_CPU0_CPUSEQUENCER_STATUS,

APOLLO_CPU1_STATUS,
DIS_IRQ_APOLLO_CPU1_LOCAL_STATUS,
DIS_IRQ_APOLLO_CPU1_CENTRAL_STATUS,
DIS_IRQ_APOLLO_CPU1_CPUSEQUENCER_STATUS,

APOLLO_CPU2_STATUS,
DIS_IRQ_APOLLO_CPU2_LOCAL_STATUS,
DIS_IRQ_APOLLO_CPU2_CENTRAL_STATUS,
DIS_IRQ_APOLLO_CPU2_CPUSEQUENCER_STATUS,

APOLLO_CPU3_STATUS,
DIS_IRQ_APOLLO_CPU3_LOCAL_STATUS,
DIS_IRQ_APOLLO_CPU3_CENTRAL_STATUS,
DIS_IRQ_APOLLO_CPU3_CPUSEQUENCER_STATUS,

ATLAS_NONCPU_STATUS,
APOLLO_NONCPU_STATUS,

ATLAS_DBG_STATUS,
ATLAS_CPUSEQUENCER_STATUS,
APOLLO_CPUSEQUENCER_STATUS,

CORTEXM3_APM_STATUS,

A7IS_STATUS,
DIS_IRQ_A7IS_LOCAL_STATUS,
DIS_IRQ_A7IS_CENTRAL_STATUS,

ATLAS_L2_STATUS,
APOLLO_L2_STATUS,

CLKSTOP_CMU_TOP_STATUS,
CLKRUN_CMU_TOP_STATUS,

RESET_CMU_TOP_STATUS,
RESET_CPUCLKSTOP_STATUS,
CLKSTOP_CMU_MIF_STATUS,
CLKRUN_CMU_MIF_STATUS,
RESET_CMU_MIF_STATUS,

DDRPHY_DLLLOCK_STATUS,

DISABLE_PLL_CMU_TOP_STATUS,
DISABLE_PLL_CMU_MIF_STATUS,

TOP_BUS_STATUS,
TOP_RETENTION_STATUS,
TOP_PWR_STATUS,
TOP_BUS_MIF_STATUS,
TOP_RETENTION_MIF_STATUS,
TOP_PWR_MIF_STATUS,

LOGIC_RESET_STATUS,
OSCCLK_GATE_STATUS,
SLEEP_RESET_STATUS,
RET_OSCCLK_GATE_STATUS,
LOGIC_RESET_MIF_STATUS,
OSCCLK_GATEMIF_STATUS,
SLEEP_RESET_MIF_STATUS,
RET_OSCCLK_GATE_MIF_STATUS,

MEMORY_TOP_STATUS,
MEMORY_TOP_ALV_STATUS,

PAD_RETENTION_LPDDR4_STATUS,
PAD_RETENTION_AUD_STATUS,
PAD_RETENTION_JTAG_STATUS,
PAD_RETENTION_BUS0_TOP_STATUS,
PAD_RETENTION_MMC2_STATUS,
PAD_RETENTION_TOP_STATUS,
PAD_RETENTION_UART_STATUS,
PAD_RETENTION_MMC0_STATUS,
PAD_RETENTION_MMC1_STATUS,
PAD_RETENTION_EBIA_STATUS,
PAD_RETENTION_EBIB_STATUS,
PAD_RETENTION_SPI_STATUS,
PAD_RETENTION_MIF_STATUS,
PAD_ISOLATION_STATUS,
PAD_RETENTION_LLI_STATUS,
PAD_RETENTION_UFS_STATUS,
PAD_ISOLATION_MIF_STATUS,
PAD_RETENTION_FSYSGENIO_STATUS,
PAD_ALV_SEL_STATUS,

XXTI_STATUS,
XXTI26_STATUS,

EXT_REGULATOR_STATUS,

GPIO_MODE_STATUS,
GPIO_MODE_FSYS0_STATUS,
GPIO_MODE_FSYS1_STATUS,
GPIO_MODE_BUS0_STATUS,
GPIO_MODE_MIF_STATUS,
GPIO_MODE_AUD_STATUS,

ATLAS_STATUS,
APOLLO_STATUS,

CLKRUN_CMU_ATLAS_STATUS,
CLKRUN_CMU_APOLLO_STATUS,
CLKSTOP_CMU_ATLAS_STATUS,
CLKSTOP_CMU_APOLLO_STATUS,

DISABLE_PLL_CMU_ATLAS_STATUS,
DISABLE_PLL_CMU_APOLLO_STATUS,

RESET_LOGIC_ATLAS_STATUS,
RESET_LOGIC_APOLLO_STATUS,

MEMORY_ATLAS_STATUS,

RESET_CMU_ATLAS_STATUS,
RESET_CMU_APOLLO_STATUS,
RESET_SLEEP_ATLAS_STATUS,
RESET_SLEEP_APOLLO_STATUS,

AUD_STATUS,
CAM0_STATUS,
CAM1_STATUS,
DISP_STATUS,
FSYS0_STATUS,
FSYS1_STATUS,
G3D_STATUS,
ISP0_STATUS,
ISP1_STATUS,
MFC_STATUS,
MSCL_STATUS,
VPP_STATUS,

CLKRUN_CMU_AUD_STATUS,
CLKRUN_CMU_BUS0_STATUS,
CLKRUN_CMU_CAM0_STATUS,
CLKRUN_CMU_CAM1_STATUS,
CLKRUN_CMU_DISP_STATUS,
CLKRUN_CMU_FSYS0_STATUS,
CLKRUN_CMU_FSYS1_STATUS,
CLKRUN_CMU_G3D_STATUS,
CLKRUN_CMU_ISP0_STATUS,
CLKRUN_CMU_ISP1_STATUS,
CLKRUN_CMU_MFC_STATUS,
CLKRUN_CMU_MSCL_STATUS,
CLKRUN_CMU_VPP_STATUS,

CLKSTOP_CMU_AUD_STATUS,
CLKSTOP_CMU_BUS0_STATUS,
CLKSTOP_CMU_CAM0_STATUS,
CLKSTOP_CMU_CAM1_STATUS,
CLKSTOP_CMU_DISP_STATUS,
CLKSTOP_CMU_FSYS0_STATUS,
CLKSTOP_CMU_FSYS1_STATUS,
CLKSTOP_CMU_G3D_STATUS,
CLKSTOP_ISP0_STATUS,
CLKSTOP_ISP1_STATUS,
CLKSTOP_CMU_MFC_STATUS,
CLKSTOP_CMU_MSCL_STATUS,
CLKSTOP_CMU_VPP_STATUS,

DISABLE_PLL_CMU_AUD_STATUS,
DISABLE_PLL_CMU_BUS0_STATUS,
DISABLE_PLL_CMU_CAM0_STATUS,
DISABLE_PLL_CMU_CAM1_STATUS,
DISABLE_PLL_CMU_DISP_STATUS,
DISABLE_PLL_CMU_FSYS0_STATUS,
DISABLE_PLL_CMU_FSYS1_STATUS,
DISABLE_PLL_CMU_G3D_STATUS,
DISABLE_PLL_CMU_ISP0_STATUS,
DISABLE_PLL_CMU_ISP1_STATUS,
DISABLE_PLL_CMU_MFC_STATUS,
DISABLE_PLL_CMU_MSCL_STATUS,
DISABLE_PLL_CMU_VPP_STATUS,

RESET_LOGIC_AUD_STATUS,
RESET_LOGIC_BUS0_STATUS,
RESET_LOGIC_CAM0_STATUS,
RESET_LOGIC_CAM1_STATUS,
RESET_LOGIC_DISP_STATUS,
RESET_LOGIC_FSYS0_STATUS,
RESET_LOGIC_FSYS1_STATUS,
RESET_LOGIC_G3D_STATUS,
RESET_LOGIC_ISP0_STATUS,
RESET_LOGIC_ISP1_STATUS,
RESET_LOGIC_MFC_STATUS,
RESET_LOGIC_MSCL_STATUS,
RESET_LOGIC_VPP_STATUS,

MEMORY_AUD_STATUS,
//MEMORY_BUS0_STATUS,
MEMORY_CAM0_STATUS,
MEMORY_CAM1_STATUS,
MEMORY_DISP_STATUS,
MEMORY_FSYS0_STATUS,
MEMORY_FSYS1_STATUS,
MEMORY_G3D_STATUS,
MEMORY_ISP0_STATUS,
MEMORY_ISP1_STATUS,
MEMORY_MFC_STATUS,
MEMORY_MSCL_STATUS,
MEMORY_VPP_STATUS,

RESET_CMU_AUD_STATUS,
RESET_CMU_BUS0_STATUS,
RESET_CMU_CAM0_STATUS,
RESET_CMU_CAM1_STATUS,
RESET_CMU_DISP_STATUS,
RESET_CMU_FSYS0_STATUS,
RESET_CMU_FSYS1_STATUS,
RESET_CMU_G3D_STATUS,
RESET_CMU_ISP0_STATUS,
RESET_CMU_ISP1_STATUS,
RESET_CMU_MFC_STATUS,
RESET_CMU_MSCL_STATUS,
RESET_CMU_VPP_STATUS,

RESET_SLEEP_BUS0_STATUS,
RESET_SLEEP_FSYS0_STATUS,
RESET_SLEEP_FSYS1_STATUS,

GPU_DVS_STATUS,

//===========================
PMU_REGS_END,
};


static uint64_t reg_offsets[] = {
//CENTRAL_MIF_STATUS
0x0244,
//RST_STAT
0x0404,
//RESET_SEQUENCER_STATUS
0x0504,

//INFORM
0x0800,
0x0804,
0x0808,
0x080C,

//PSHOLD
0x0820,
0x0820,

//ATLAS0_STATUS
0x2004,
0x2024,
0x2044,
0x2064,

//ATLAS1_STATUS
0x2084,
0x20A4,
0x20C4,
0x20E4,

//ATLAS2_STATUS
0x2104,
0x2124,
0x2144,
0x2164,

//ATLAS3_STATUS
0x2184,
0x21A4,
0x21C4,
0x21E4,

//APOLLO0_STATUS
0x2204,
0x2224,
0x2244,
0x2264,

//APOLLO1_STATUS
0x2284,
0x22A4,
0x22C4,
0x22E4,

//APOLLO2_STATUS
0x2304,
0x2324,
0x2344,
0x2364,

//APOLLO3_STATUS
0x2384,
0x23A4,
0x23C4,
0x23E4,

//ATLAS_NONCPU
0x2404,
//APOLLO_NONCPU
0x2424,

//ATLAS_DBG_STATUS
0x2444,
//ATLAS_SEQUENCER
0x2484,
//APOLLO_SEQUENCER
0x24A4,

//CORTEXM3
0x2504,

//A7IS
0x2584,
0x25A4,
0x25C4,

//ATLAS_L2
0x2604,
//APOLLO_L2
0x2624,

//CLKSTOP_CMU_TOP
0x2804,
//CLKRUN_CMU_TOP
0x2824,
//RESET_CMU_TOP
0x2864,
//RESET_CLKSTOP
0x28E4,
//CLKSTOP_CMU_MIF
0x2904,
//CLKRUN_CMU_MIF
0x2924,
//RESET_CMU_MIF
0x2964,

//DDRPHY_DLLLOCK
0x29C4,

//DISABLE_PLL_CMU_TOP
0x2A04,
//DISABLE_PLL_CMU_MIF
0x2B04,

//TOP
0x2C04,
0x2C24,
0x2C44,
0x2C84,
0x2CA4,
0x2CC4,


//LOGIC_RESET_STATUS,
0x2D04,
0x2D24,
0x2D44,
0x2D64,
0x2D84,
0x2DA0,
0x2DC4,
0x2DE4,

//MEMORY_TOP
0x2E04,
0x2E24,

//PAD_RETENTION
0x3004,
0x3024,
0x3044,
0x3064,
0x30C4,
0x3104,
0x3124,
0x3144,
0x3164,
0x3184,
0x31A4,
0x31C4,
0x31E4,
0x3204,
0x3224,
0x3264,
0x3284,
0x32A4,
0x3304,

//XXTI
0x3424,
0x3444,

//EXT_REGULATOR
0x3604,

//GPIO_MODE
0x3804,
0x3824,
0x3844,
0x3864,
0x3904,
0x39E4,

//ATLAS_STATUS
0x3A04,
//APOLLO_STATUS
0x3A24,

//CLKRUNSTOP_ATLAPL
0x3A44,
0x3A64,
0x3A84,
0x3AA4,

//DISABLE_PLL_ATLAPL
0x3AC4,
0x3AE4,

//RESET_LOGICATLAPL
0x3B04,
0x3B24,

//MEMORY_ATLAS
0x3B44,

//RESET_SMU_SLEEP_ATLAPL
0x3B64,
0x3B84,
0x3BA4,
0x3BC4,

//SUBSYSTEMS
0x4004,
0x4044,
0x4064,
0x4084,
0x40A4,
0x40C4,
0x4104,
0x4144,
0x4184,
0x41A4,
0x41C4,
0x41E4,

//CLKRUN_CMU
0x4204,
0x4224,
0x4244,
0x4264,
0x4284,
0x42A4,
0x42C4,
0x4304,
0x4344,
0x4384,
0x43A4,
0x43C4,
0x43E4,

//CLKSTOP_CMU
0x4404,
0x4424,
0x4444,
0x4464,
0x4484,
0x44C4,
0x44A4,
0x4504,
0x4544,
0x4584,
0x45A4,
0x45C4,
0x45E4,

//DISABLE_PLL_CMU
0x4604,
0x4624,
0x4644,
0x4664,
0x4684,
0x46A4,
0x46C4,
0x4704,
0x4744,
0x4784,
0x47A4,
0x47C4,
0x47E4,

//RESET_LOGIC
0x4804,
0x4824,
0x4844,
0x4864,
0x4884,
0x48A4,
0x48C4,
0x4904,
0x4944,
0x4984,
0x49A4,
0x49C4,
0x49E4,

//MEMORY
0x4A04,
//0x4A24,
0x4A44,
0x4A64,
0x4A84,
0x4AA4,
0x4AC4,
0x4B04,
0x4B44,
0x4B84,
0x4BA4,
0x4BC4,
0x4BE4,

//RESET_CMU
0x4C04,
0x4C24,
0x4C44,
0x4C64,
0x4C84,
0x4CA4,
0x4CC4,
0x4D04,
0x4D54,
0x4D84,
0x4DA4,
0x4DC4,
0x4DE4,

//RESET_SLEEP
0x4E24,
0x4EA4,
0x4EC4,

//RESET_GPU
0x6104
};

static char *reg_names[] = { 
"CENTRAL_SEQ_MIF_STATUS",
"RST_STATUS",
"RESET_SEQUENCER_STATUS",

"INFORM0",
"INFORM1",
"INFORM2",
"INFORM3",

"PS_HOLD_HW_TRIP",
"PS_HOLD_SW_TRIP",

"ATLAS_CPU0_STATUS",
"DIS_IRQ_ATLAS_CPU0_LOCAL_STATUS",
"DIS_IRQ_ATLAS_CPU0_CENTRAL_STATUS",
"DIS_IRQ_ATLAS_CPU0_CPUSEQUENCER_STATUS",

"ATLAS_CPU1_STATUS",
"DIS_IRQ_ATLAS_CPU1_LOCAL_STATUS",
"DIS_IRQ_ATLAS_CPU1_CENTRAL_STATUS",
"DIS_IRQ_ATLAS_CPU1_CPUSEQUENCER_STATUS",

"ATLAS_CPU2_STATUS",
"DIS_IRQ_ATLAS_CPU2_LOCAL_STATUS",
"DIS_IRQ_ATLAS_CPU2_CENTRAL_STATUS",
"DIS_IRQ_ATLAS_CPU2_CPUSEQUENCER_STATUS",

"ATLAS_CPU3_STATUS",
"DIS_IRQ_ATLAS_CPU3_LOCAL_STATUS",
"DIS_IRQ_ATLAS_CPU3_CENTRAL_STATUS",
"DIS_IRQ_ATLAS_CPU3_CPUSEQUENCER_STATUS",

"APOLLO_CPU0_STATUS",
"DIS_IRQ_APOLLO_CPU0_LOCAL_STATUS",
"DIS_IRQ_APOLLO_CPU0_CENTRAL_STATUS",
"DIS_IRQ_APOLLO_CPU0_CPUSEQUENCER_STATUS",

"APOLLO_CPU1_STATUS",
"DIS_IRQ_APOLLO_CPU1_LOCAL_STATUS",
"DIS_IRQ_APOLLO_CPU1_CENTRAL_STATUS",
"DIS_IRQ_APOLLO_CPU1_CPUSEQUENCER_STATUS",

"APOLLO_CPU2_STATUS",
"DIS_IRQ_APOLLO_CPU2_LOCAL_STATUS",
"DIS_IRQ_APOLLO_CPU2_CENTRAL_STATUS",
"DIS_IRQ_APOLLO_CPU2_CPUSEQUENCER_STATUS",

"APOLLO_CPU2_STATUS",
"DIS_IRQ_APOLLO_CPU2_LOCAL_STATUS",
"DIS_IRQ_APOLLO_CPU2_CENTRAL_STATUS",
"DIS_IRQ_APOLLO_CPU2_CPUSEQUENCER_STATUS",

"ATLAS_NONCPU_STATUS",
"APOLLO_NONCPU_STATUS",

"ATLAS_DBG_STATUS",
"ATLAS_CPUSEQUENCER_STATUS",
"APOLLO_CPUSEQUENCER_STATUS",

"CORTEXM3_APM_STATUS",

"A7IS_STATUS",
"DIS_IRQ_A7IS_LOCAL_STATUS",
"DIS_IRQ_A7IS_CENTRAL_STATUS",

"ATLAS_L2_STATUS",
"APOLLO_L2_STATUS",

"CLKSTOP_CMU_TOP_STATUS",
"CLKRUN_CMU_TOP_STATUS",

"RESET_CMU_TOP_STATUS",

"RESET_CPUCLKSTOP_STATUS",
"CLKSTOP_CMU_MIF_STATUS",

"CLKRUN_CMU_MIF_STATUS",
"RESET_CMU_MIF_STATUS",

"DDRPHY_DLLLOCK_STATUS",

"DISABLE_PLL_CMU_TOP_STATUS",

"DISABLE_PLL_CMU_MIF_STATUS",

"TOP_BUS_STATUS",
"TOP_RETENTION_STATUS",
"TOP_PWR_STATUS",
"TOP_BUS_MIF_STATUS",

"TOP_RETENTION_MIF_STATUS",

"TOP_PWR_MIF_STATUS",

"LOGIC_RESET_STATUS",


"OSCCLK_GATE_STATUS",

"SLEEP_RESET_STATUS",

"RET_OSCCLK_GATE_STATUS",

"LOGIC_RESET_MIF_STATUS",

"OSCCLK_GATEMIF_STATUS",


"SLEEP_RESET_MIF_STATUS",


"RET_OSCCLK_GATE_MIF_STATUS",

"MEMORY_TOP_STATUS",

"MEMORY_TOP_ALV_STATUS",

"PAD_RETENTION_LPDDR4_STATUS",

"PAD_RETENTION_AUD_STATUS",

"PAD_RETENTION_JTAG_STATUS",

"PAD_RETENTION_BUS0_TOP_STATUS",

"PAD_RETENTION_MMC2_STATUS",

"PAD_RETENTION_TOP_STATUS",

"PAD_RETENTION_UART_STATUS",

"PAD_RETENTION_MMC0_STATUS",

"PAD_RETENTION_MMC1_STATUS",

"PAD_RETENTION_EBIA_STATUS",

"PAD_RETENTION_EBIB_STATUS",

"PAD_RETENTION_SPI_STATUS",

"PAD_RETENTION_MIF_STATUS",

"PAD_ISOLATION_STATUS",

"PAD_RETENTION_LLI_STATUS",

"PAD_RETENTION_UFS_STATUS",

"PAD_ISOLATION_MIF_STATUS",

"PAD_RETENTION_FSYSGENIO_STATUS",

"PAD_ALV_SEL_STATUS",

"XXTI_STATUS",

"XXTI26_STATUS",

"EXT_REGULATOR_STATUS",

"GPIO_MODE_STATUS",

"GPIO_MODE_FSYS0_STATUS",

"GPIO_MODE_FSYS1_STATUS",

"GPIO_MODE_BUS0_STATUS",

"GPIO_MODE_MIF_STATUS",

"GPIO_MODE_AUD_STATUS",

"ATLAS_STATUS",

"APOLLO_STATUS",

"CLKRUN_CMU_ATLAS_STATUS",

"CLKRUN_CMU_APOLLO_STATUS",

"CLKSTOP_CMU_ATLAS_STATUS",

"CLKSTOP_CMU_APOLLO_STATUS",

"DISABLE_PLL_CMU_ATLAS_STATUS",

"DISABLE_PLL_CMU_APOLLO_STATUS",

"RESET_LOGIC_ATLAS_STATUS",

"RESET_LOGIC_APOLLO_STATUS",

"MEMORY_ATLAS_STATUS",

"RESET_CMU_ATLAS_STATUS",

"RESET_CMU_APOLLO_STATUS",

"RESET_SLEEP_ATLAS_STATUS",

"RESET_SLEEP_APOLLO_STATUS",

"AUD_STATUS",

"CAM0_STATUS",

"CAM1_STATUS",

"DISP_STATUS",

"FSYS0_STATUS",

"FSYS1_STATUS",

"G3D_STATUS",

"ISP0_STATUS",

"ISP1_STATUS",

"MFC_STATUS",

"MSCL_STATUS",

"VPP_STATUS",

"CLKRUN_CMU_AUD_STATUS",

"CLKRUN_CMU_BUS0_STATUS",

"CLKRUN_CMU_CAM0_STATUS",

"CLKRUN_CMU_CAM1_STATUS",

"CLKRUN_CMU_DISP_STATUS",

"CLKRUN_CMU_FSYS0_STATUS",

"CLKRUN_CMU_FSYS1_STATUS",

"CLKRUN_CMU_G3D_STATUS",

"CLKRUN_CMU_ISP0_STATUS",

"CLKRUN_CMU_ISP1_STATUS",

"CLKRUN_CMU_MFC_STATUS",

"CLKRUN_CMU_MSCL_STATUS",

"CLKRUN_CMU_VPP_STATUS",

"CLKSTOP_CMU_AUD_STATUS",

"CLKSTOP_CMU_BUS0_STATUS",

"CLKSTOP_CMU_CAM0_STATUS",

"CLKSTOP_CMU_CAM1_STATUS",

"CLKSTOP_CMU_DISP_STATUS",

"CLKSTOP_CMU_FSYS0_STATUS",

"CLKSTOP_CMU_FSYS1_STATUS",

"CLKSTOP_CMU_G3D_STATUS",

"CLKSTOP_ISP0_STATUS",

"CLKSTOP_ISP1_STATUS",

"CLKSTOP_CMU_MFC_STATUS",

"CLKSTOP_CMU_MSCL_STATUS",

"CLKSTOP_CMU_VPP_STATUS",

"DISABLE_PLL_CMU_AUD_STATUS",

"DISABLE_PLL_CMU_BUS0_STATUS",

"DISABLE_PLL_CMU_CAM0_STATUS",

"DISABLE_PLL_CMU_CAM1_STATUS",

"DISABLE_PLL_CMU_DISP_STATUS",

"DISABLE_PLL_CMU_FSYS0_STATUS",

"DISABLE_PLL_CMU_FSYS1_STATUS",

"DISABLE_PLL_CMU_G3D_STATUS",

"DISABLE_PLL_CMU_ISP0_STATUS",

"DISABLE_PLL_CMU_ISP1_STATUS",

"DISABLE_PLL_CMU_MFC_STATUS",

"DISABLE_PLL_CMU_MSCL_STATUS",

"DISABLE_PLL_CMU_VPP_STATUS",

"RESET_LOGIC_AUD_STATUS",

"RESET_LOGIC_BUS0_STATUS",

"RESET_LOGIC_CAM0_STATUS",

"RESET_LOGIC_CAM1_STATUS",

"RESET_LOGIC_DISP_STATUS",

"RESET_LOGIC_FSYS0_STATUS",

"RESET_LOGIC_FSYS1_STATUS",

"RESET_LOGIC_G3D_STATUS",

"RESET_LOGIC_ISP0_STATUS",

"RESET_LOGIC_ISP1_STATUS",

"RESET_LOGIC_MFC_STATUS",

"RESET_LOGIC_MSCL_STATUS",

"RESET_LOGIC_VPP_STATUS",

"MEMORY_AUD_STATUS",

//"MEMORY_BUS0_STATUS",

"MEMORY_CAM0_STATUS",

"MEMORY_CAM1_STATUS",

"MEMORY_DISP_STATUS",

"MEMORY_FSYS0_STATUS",

"MEMORY_FSYS1_STATUS",

"MEMORY_G3D_STATUS",

"MEMORY_ISP0_STATUS",

"MEMORY_ISP1_STATUS",

"MEMORY_MFC_STATUS",

"MEMORY_MSCL_STATUS",

"MEMORY_VPP_STATUS",

"RESET_CMU_AUD_STATUS",

"RESET_CMU_BUS0_STATUS",

"RESET_CMU_CAM0_STATUS",

"RESET_CMU_CAM1_STATUS",

"RESET_CMU_DISP_STATUS",
"RESET_CMU_FSYS0_STATUS",

"RESET_CMU_FSYS1_STATUS",

"RESET_CMU_G3D_STATUS",

"RESET_CMU_ISP0_STATUS",

"RESET_CMU_ISP1_STATUS",

"RESET_CMU_MFC_STATUS",

"RESET_CMU_MSCL_STATUS",

"RESET_CMU_VPP_STATUS",

"RESET_SLEEP_BUS0_STATUS",

"RESET_SLEEP_FSYS0_STATUS",

"RESET_SLEEP_FSYS1_STATUS",

"GPU_DVS_STATUS"
};


#endif
