dtb-$(CONFIG_ARCH_EXYNOS7) += kmax-reva-sdcard.dtb
dtb-$(CONFIG_ARCH_EXYNOS7) += kmax-revb-sdcard.dtb
dtb-$(CONFIG_ARCH_EXYNOS7) += kmax-reva-ufs.dtb
dtb-$(CONFIG_ARCH_EXYNOS7) += kmax-revb-ufs.dtb
dtb-$(CONFIG_ARCH_EXYNOS7) += kmax-revb-ubuntu.dtb


always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
